<jsp:include page="yui/build/yahoo/yahoo.js"/>
<jsp:include page="yui/build/dom/dom.js"/>
<jsp:include page="yui/build/event/event.js"/>
<jsp:include page="yui/build/logger/logger.js"/>
<jsp:include page="yui/build/animation/animation.js"/>
<jsp:include page="yui/build/connection/connection.js" />
<jsp:include page="yui/build/container/container.js" />
<jsp:include page="yui/build/connection/connection.js" />
<jsp:include page="yui/build/tabview/tabview.js"/>
<jsp:include page="yui/build/yahoo-dom-event/yahoo-dom-event.js"/>
<jsp:include page="yui/build/autocomplete/autocomplete-min.js"/>
<jsp:include page="javascript/overlib/overlib.js"/>
<jsp:include page="javascript/webstart/webstart.js"/>